global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'tt-collector'
    static_configs:
      - targets: ['tt-collector:3004']
  
  - job_name: 'fb-collector'
    static_configs:
      - targets: ['fb-collector:3005']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3010']

  - job_name: 'report'
    static_configs:
      - targets: ['report:3020']