{
 "title": "Main",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Collector Event Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(collector_received_events_count[1m]))"
    },
    {
     "expr": "sum(rate(collector_processed_events_count[1m]))"
    },
    {
     "expr": "sum(rate(collector_failed_events_count[1m]))"
    }
   ]
  },
  { "title": "Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Gateway Received Events",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(gateway_received_events_count[1m]))"
    }
   ]
  },
  {
   "title": "Gateway Processed Events",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(gateway_processed_events_count[1m]))"
    }
   ]
  },
  {
   "title": "Gateway Failed Events",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(rate(gateway_failed_events_count[1m]))"
    }
   ]
  }
 ]
}